#!/usr/bin/env bash
# Script installs Nginx on 246646-web-01

# Updating Packages before  Installing
sudo apt-get update
sudo apt-get -y install nginx

# Configuring the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start
