#!/usr/bin/env bash
# Installs Nginx and configures it so that its HTTP response contains a custom header (on web-01 and web-02)


# Updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/etginc.tech permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404  error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

# Creating HTTP response header
sudo sed -i "sesrver_name _:/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing for syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
