#!/usr/bin/env bash
# Script installs and configures HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers

#Update the package list
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend etginc-frontend
        bind *:80
        mode http
        default_backend etginc-backend
backend nana-aba-backend
        balance roundrobin
        server 246646-web-01 100.25.111.181 check
        server 246646-web-02 174.129.171.238 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
