#!/usr/bin/env bash
# Script loops through 1 to 10 using while displays bad luck for the 4th loop iteration displays good luck for the 8th loop iteration displays Best School for the other iterations

e=1

while [ $e -le 10 ]
do
    if [ $e -eq 4 ]
    then
        echo "bad luck"
    elif [ $e -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((e++))
done
