#!/usr/bin/env bash
#Script gives you information about the school file.

e=school
if [ -e $e ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -s $e ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -f $e ]; then
    echo "school is a regular file"
fi
